### ISSUE TITLE
regarding installation  

### ISSUE THREAD

**Issue by maraboinavamshi** [sgeisler/termgraph#6]

**Comment by maraboinavamshi** [comment]
how to install graph in python 3.6
iam getting trouble while installing it .please help me os windows 10

**Comment by sgeisler** [comment]
Since I'm not using windows myself I don't know how you install python packages there and won't be able to help you without more information about your setup. Are you using `pip` like on linux?

PS: Besides that, please don't use this library for anything important, it was more or less hacked together in a couple of evenings. But PRs are always welcome.

**Comment by sgeisler** [comment]
see #11
